### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by shanow7** [kennbroorg/iKy#23]
hi I've this

 iKy/frontend$ npm start

> ngx-admin-iKy@2.0.0 start /home/kali/OSINT/Iky/iKy/frontend
> ng serve

Job name "..getProjectMetadata" does not exist.
Error: Job name "..getProjectMetadata" does not exist.
    at Observable._subscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)                                   
    at Observable._trySubscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:44:25)                                  
    at Observable.subscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:30:22)                                      
    at /home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:22:31                                                       
    at Object.subscribeToResult (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)                      
    at SwitchMapSubscriber._innerSub (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)                    
    at SwitchMapSubscriber._next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)                        
    at SwitchMapSubscriber.Subscriber.next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)                       
    at SwitchMapSubscriber.notifyNext (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)                   
    at InnerSubscriber._next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)                                
    at InnerSubscriber.Subscriber.next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)                           
    at /home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28                                                       
    at Object.subscribeToResult (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)                      
    at SwitchMapSubscriber._innerSub (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)                    
    at SwitchMapSubscriber._next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)                        
    at SwitchMapSubscriber.Subscriber.next (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)                       
    at DefaultIfEmptySubscriber._complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/defaultIfEmpty.js:45:30)          
    at DefaultIfEmptySubscriber.Subscriber.complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:78:18)              
    at TakeSubscriber.Subscriber._complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:96:26)                       
    at TakeSubscriber.Subscriber.complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:78:18)                        
    at FilterSubscriber.Subscriber._complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:96:26)                     
    at FilterSubscriber.Subscriber.complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:78:18)                      
    at MergeMapSubscriber._complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:87:30)                      
    at MergeMapSubscriber.Subscriber.complete (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:78:18)                    
    at Observable._subscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToArray.js:8:20)                           
    at Observable._trySubscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:44:25)                                  
    at Observable.subscribe (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Observable.js:30:22)                                      
    at MergeMapOperator.call (/home/kali/OSINT/Iky/iKy/frontend/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:39:23)                             
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-admin-iKy@2.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-admin-iKy@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kali/.npm/_logs/2020-08-25T19_32_24_095Z-debug.log

can you help?

**Comment by KennBro** [comment]
Surely an error must have occurred with the npm install command.
Do you have any output from that command?

Usually this error
```
This is probably not a problem with npm. There is likely additional logging output above
```
appears when OS dependencies are missing that have nothing to do with nodejs, npm or the project itself

**Comment by shanow7** [comment]
iKy/frontend$ npm start&gt; ngx-admin-iKy@2.0.0 start /home/kali/OSINT/iKy/frontend&gt; ng serveBrowserslist: caniuse-lite is outdated. Please run the following command: `npm update`10% building 3/3 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/ℹ ｢wds｣: webpack output is served from /ℹ ｢wds｣: 404s will fallback to //index.htmlchunk {app-pages-pages-module} app-pages-pages-module.js, app-pages-pages-module.js.map (app-pages-pages-module) 32.3 MB&nbsp; [rendered]&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;chunk {main} main.js, main.js.map (main) 2.85 MB [initial] [rendered]chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 480 kB [initial] [rendered]&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;chunk {runtime} runtime.js, runtime.js.map (runtime) 9.01 kB [entry] [rendered]chunk {scripts} scripts.js, scripts.js.map (scripts) 1.47 MB [entry] [rendered]chunk {styles} styles.js, styles.js.map (styles) 4.87 MB [initial] [rendered]chunk {vendor} vendor.js, vendor.js.map (vendor) 7.82 MB [initial] [rendered]Date: 2020-08-25T20:12:42.545Z - Hash: 38b0f56b6acb1542a27c - Time: 80167ms** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **ℹ ｢wdm｣: Compiled successfully.Temat: Re: [kennbroorg/iKy] npm start error (#23)Data: 2020-08-26 19:18Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "jan bor" ; "Author" ; 
Surely an error must have occurred with the npm install command.
Do you have any output from that command?
Usually this error
This is probably not a problem with npm. There is likely additional logging output above

appears when OS dependencies are missing that have nothing to do with nodejs, npm or the project itself

**Comment by shanow7** [comment]
I've problem with ./celery.sh&nbsp;can you help?Temat: Re: [kennbroorg/iKy] npm start error (#23)Data: 2020-08-26 19:18Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "jan bor" ; "Author" ; 
Surely an error must have occurred with the npm install command.
Do you have any output from that command?
Usually this error
This is probably not a problem with npm. There is likely additional logging output above

appears when OS dependencies are missing that have nothing to do with nodejs, npm or the project itself

**Comment by KennBro** [comment]
What is the problem with celery? Give me some information about that.
Anyway celery is the backend of the project.  And npm belongs to the frontend dependencies.

**Comment by shanow7** [comment]
how can I stop redis-server the celery probably doesn't workTemat: Re: [kennbroorg/iKy] npm start error (#23)Data: 2020-08-27 16:12Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "jan bor" ; "Author" ; 
What is the problem with celery? Give me some information about that.
Anyway celery is the backend of the project.  And npm belongs to the frontend dependencies.

**Comment by KennBro** [comment]
If you run 
```
redis-server
```
in a terminal, just press Ctrl-C in that terminal

**Comment by shanow7** [comment]
thx :)can you try search this email&nbsp;jacekkuzmicki.jk@gmail.com on iky&nbsp;because he did not find anything for me and I know that 2 profiles are registered on this email, one on fb and the other on instagramTemat: Re: [kennbroorg/iKy] npm start error (#23)Data: 2020-08-27 16:44Nadawca: "Kenn" Adresat: "kennbroorg/iKy" ; DW: "jan bor" ; "Author" ; 
If you run
redis-server

in a terminal, just press Ctrl-C in that terminal

**Comment by KennBro** [comment]
Check the new documentation about the installation without nodejs and angular.
https://github.com/kennbroorg/iKy#installation
