### ISSUE TITLE
Errno22 invalid argument

### ISSUE THREAD

**Issue by lemixtape** [kennbroorg/iKy#33]
I am running Windows 10 and Docker Desktop. I have Python 3.6.1 installed.

I ran the docker-compose up --build command but get this error when building the frontend. 

Building frontend
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\D:\\Docker\\iKy\\frontend\\node_modules\\.bin\\JSONStream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 346, in ensure_image_exists
  File "compose\service.py", line 1125, in build
  File "site-packages\docker\api\build.py", line 160, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\Docker\iKy\frontend\node_modules\.bin\JSONStream
[23944] Failed to execute script docker-compose

Does anyone have a solution?

**Comment by KennBro** [comment]
I have no experience in Windows with docker. But I'll try to get someone who can test it.

But you can try the installation through WSL that I did test it

**Comment by lemixtape** [comment]
I did try it and had several issues. Do you have specific versions of
Python that I need to install? I believe I have 3.6 but encountered many
issues with packages not being available.

I remain available should you want me to test new releases.

David

**Comment by KennBro** [comment]
Python 3.7 or superior. (For async support). I use python 3.8
For easy installation follow the instructions in this [tweet](https://twitter.com/kennbroorg/status/1329430226380627968?s=20)
And thanks for your offer, I always need testers.

KennBro

**Comment by KennBro** [comment]
Reopen it if necessary
