### ISSUE TITLE
Jinja error

### ISSUE THREAD

**Issue by Chomikmarkus** [kennbroorg/iKy#80]
Hello!
Having trouble running iky OS:Ubuntu 20.04 python version 3.8
Output from error: 
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/iKy/backend# python3 app.py -e prod
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from factories.application import create_application
  File "/opt/iKy/backend/factories/application.py", line 2, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/iKy/backend#

**Comment by KennBro** [comment]
Fix on commit 1255a8835f29a2a2a28b9da38af0a61a3b636141
